# -*- coding: UTF-8 -*-
"""
Module that defines project-wide constants.
"""

__author__ = 'kensk8er1017@gmail.com'

LANG_CODE2LANGUAGE = {
    'af': 'Afrikaans',
    'sq': 'Albanian',
    'am': 'Amharic',
    'ar': 'Arabic',
    'bg': 'Bulgarian',
    'zh': 'Chinese',
    'hr': 'Croatian',
    'cs': 'Czech',
    'da': 'Danish',
    'nl': 'Dutch',
    'en': 'English',
    'eo': 'Esperanto',
    'et': 'Estonian',
    'fa': 'Farsi',
    'fi': 'Finnish',
    'fr': 'French',
    'de': 'German',
    'el': 'Greek',
    'ht': 'Creole',
    'he': 'Hebrew',
    'hi': 'Hindi',
    'hu': 'Hungarian',
    'is': 'Icelandic',
    'id': 'Indonesian',
    'it': 'Italian',
    'ja': 'Japanese',
    'kn': 'Kannada',
    'ko': 'Korean',
    'la': 'Latin',
    'lt': 'Lithuanian',
    'mg': 'Malagasy',
    'ml': 'Malayalam',
    'mi': 'Maori',
    'mr': 'Marathi',
    'my': 'Myanmar',
    'ne': 'Nepali',
    'no': 'Norwegian',
    'pl': 'Polish',
    'pt': 'Portuguese',
    'ro': 'Romanian',
    'ru': 'Russian',
    'sr': 'Serbian',
    'sk': 'Slovak',
    'sl': 'Slovene',
    'so': 'Somali',
    'es': 'Spanish',
    'sv': 'Swedish',
    'tl': 'Tagalog',
    'te': 'Telugu',
    'th': 'Thai',
    'tr': 'Turkish',
    'vi': 'Vietnamese',
    'xh': 'Xhosa',
}
